export const GET_CHOCOLATES = "GET_CHOCOLATES";
export const GET_CHOCOLATES_SUCCESS = "GET_CHOCOLATES_SUCCESS";
export const GET_CHOCOLATES_FAILURE = "GET_CHOCOLATES_FAILURE";
export const GET_CHOCOLATES_BYID = "GET_CHOCOLATES_BYID";
export const GET_CHOCOLATES_BYID_SUCCESS = "GET_CHOCOLATES_BYID_SUCCESS";
export const GET_CHOCOLATES_BYID_FAILURE = "GET_CHOCOLATES_BYID_FAILURE";
export const SET_QUERY = "SET_QUERY";
